version: '3.8'

services:
  web: 
    build:
      context: .
      dockerfile: ./Dockerfile
    image: niotir/fastapi_dithering_web
    command: uvicorn main:app --reload  --host 0.0.0.0
    volumes: 
      - .:/app
    ports: 
      - 8010:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis: 
    image: redis:8.2.1-alpine
  
  celery_worker:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: niotir/fastapi_dithering_worker
    command: celery -A tasks worker --loglevel=info
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

